baseURL: https://databiosphere.github.io/databiosphere-website/
languageCode: en-us
title: Data Biosphere
theme: hugo-fresh

params:
  navbarlogo:
  # Logo (from /images/logos/___)
   image: logo.png
   link: /
  font:
    name: "Open Sans"
    sizes: [500,600]
  hero:
    # Main hero title
    title: the Data Biosphere
    # Hero subtitle (optional)
    subtitle: creating a vibrant ecosystem of interoperable modules and data environments for the biomedical community
    # Button text
    buttontext: About
    # Where the main hero button links to
    buttonlink: "#About"
    button2text: Data Environments
    # Where the main hero button links to
    button2link: "#Data Environments"
    button3text: Modular Components
    # Where the main hero button links to
    button3link: "#Modular Components"
    # Hero image (from /images/___)
    image: logo.png
    # Footer logos (from /images/logos/clients/___.svg)
    clientlogos:
    - broad
    - chicago
    - ucsc
    - vanderbilt
    - verily
  # Customizable navbar. For a dropdown, add a "sublinks" list.
  navbar:
  - title: About
    url: '#About'
  - title: Data Environments
    url: '#Data Environments'
  - title: Modular Components
    url: '#Modular Components'
  - title: Getting Involved
    url: '#Getting Involved'
  # - title: Dropdown
  #   sublinks:
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  #   - title: Dropdown item
  #     url: /
  # - title: Log in
  #   url: /
  # - title: Sign up
  #   url: /
  #   button: true
  sidebar:
    # Logo (from /images/logos/___.svg)
    logo: fresh-square
    sections:
    - title: User
      icon: user
      links:
      - text: Profile
        url: /
      - text: Account
        url: /
      - text: Settings
        url: /
    - title: Messages
      icon: envelope
      links:
      - text: Inbox
        url: /
      - text: Compose
        url: /
    - title: Images
      icon: image
      links:
      - text: Library
        url: /
      - text: Upload
        url: /
    - title: Settings
      icon: cog
      links:
      - text: User settings
        url: /
      - text: App settings
        url: /
  section2:
    title: About
    subtitle:
    features:
    - title: Problems the Data Biosphere is trying to solve
      text: 'Modern technologies produce enormous datasets in the life sciences which researchers struggle to manage.  Genomics dataset sizes can easily be in the terabyte or even petabyte range, making it difficult to extract meaning for all but a few.  The obvious solution is cloud-based data storage and computation designed to make biomedical research more accessible. But, how should these systems be designed?  In our [blog post](https://medium.com/@benedictpaten/a-data-biosphere-for-biomedical-research-d212bbfae95d) we explore the motivations for creating the Data Biosphere organization and the approaches we think are key to its missions.'
      # Icon (from /images/illustrations/icons/___.svg)
      icon: laptop-globe
    - title: The principles of the Data Biosphere
      text: 'We created the Data Biosphere with the idea of cultivating a vibrant ecosystem of modular and interoperable components that can be assembled into diverse data environments. The Data Biosphere is based on four governing principles: it should be: 1. modular, composed of functional components with well-specified interfaces; 2. community-driven, created by many groups to foster a diversity of ideas; 3. open, developed under open-source licenses that enable extensibility and reuse, with users able to add custom, proprietary modules as needed; and 4. standards-based, consistent with standards developed by coalitions such as the [Global Alliance for Genomics and Health (GA4GH)](https://www.ga4gh.org).'
      icon: mobile-feed
    - title: Modules and Data Environments in the Data Biosphere
      text: 'The Data Biosphere will work best if it is designed around key modular components — each having discrete capabilities and clear rules of interaction, and each served by multiple alternative implementations.  In the Data Biosphere, Modules Components are the critical building blocks, but they are not alone enough to meet the needs of the biomedical community.  In addition we need Data Environments, or suites of services assembled from the Modular Components, that allow users to carry out a set of related tasks in an easy way.  We envision multiple Data Environments, targeting a diversity of communities, use cases, and data types.'
      icon: doc-sync
    - title: The state of the Data Biosphere
      text: 'The biomedical community has already begun the work of creating the Data Biosphere. We, along with many others, are actively contributing to the GA4GH definitions of standard interfaces and are currently developing Modular Components and data environments as part of the Data Biosphere effort. We share many of our reusable modules on our [GitHub organization](https://github.com/DataBiosphere) and full Data Environments are already operational and used by many researchers each and every day.  We invite further contributions by the community and encourage you to contact us to learn more.'
      icon: plug-cloud
  section1:
    title: Data Environments
    subtitle: use ready-to-go Data Biosphere systems
    tiles:
    - title: Gen3
      icon: mouse-globe
      text: Use Gen3 to build your own Data Environment
      url: https://gen3.org/
      buttonText: Use Gen3
    - title: Terra
      icon: laptop-cloud
      text: Use Terra to find, analyze, and explore data
      url: https://terra.bio/
      buttonText: Ues Terra
    - title: Dockstore
      icon: plug-cloud
      text: Create, share, and use bioinformatics workflows
      url: https://dockstore.org/
      buttonText: Use Dockstore
  section3:
    title: Modular Components
    subtitle: The building blocks of the Data Biosphere, explore our GitHub organization to see modules shared with the communmity.
    image: illustrations/databiosphere.png
    buttonText: Data Biosphere on GitHub
    buttonLink: "https://github.com/DataBiosphere"
#  section4:
#    title: Users
#    subtitle: Lorem ipsum sit dolor amet is a dummy text used by typography industry
#    clients:
#    - name: Irma Walters
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Accountant
#      img: 1
#    - name: John Bradley
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: Financial Analyst
#      img: 2
#    - name: Gary Blackman
#      quote: Lorem ipsum dolor sit amet, elit deleniti dissentias quo eu, hinc minim appetere te usu, ea case duis scribentur has. Duo te consequat elaboraret, has quando suavitate at.
#      job: HR Manager
#      img: 3
  section5:
    title: Getting Involved
    subtitle:
#  section6:
#    title: Getting Involved
#    subtitle:
#    features:
#    - title: Powerful and unified interface
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      # Icon (from /images/illustrations/icons/___.svg)
#      icon: laptop-globe
#    - title: Cross-device synchronisation
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: doc-sync
#    - title: Nomad system
#      text: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin ornare magna eros, eu pellentesque tortor vestibulum ut. Maecenas non massa sem. Etiam finibus odio quis feugiat facilisis.
#      icon: mobile-feed
#  footer:
#    # Logo (from /images/logos/___)
#    logo: fresh-white-alt.svg
#    # Social media links (GitHub, Twitter, etc.). All are optional.
#    socialmedia:
#    - link: https://github.com/lucperkins/github-fresh
#      # Icons are from Font Awesome
#      icon: github
#    - link: https://dribbble.com/#
#      icon: dribbble
#    - link: https://facebook.com/#
#      icon: facebook
#    - link: https://twitter.com/lucperkins
#      icon: twitter
#    - link: https://bitbucket.org/#
#      icon: bitbucket
#    bulmalogo: false
#    quicklinks:
#      column1:
#        title: "Product"
#        links:
#        - text: Discover features
#          link: /
#        - text: Why choose our product?
#          link: /
#        - text: Compare features
#          link: /
#        - text: Our roadmap
#          link: /
#        - text: Request features
#          link: /
#      column2:
#        title: "Docs"
#        links:
#        - text: Get started
#          link: /
#        - text: User guides
#          link: /
#        - text: Admin guide
#          link: /
#        - text: Developers
#          link: /
#      column3:
#        title: "Blog"
#        links:
#        - text: Latest news
#          link: /
#        - text: Tech articles
#          link: /
#        - text: Video blog
#          link: /
