language: go

go:
  - 1.10

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"

install:
  - go get github.com/magefile/mage
  - go get -u -d github.com/magefile/mage
  - cd ${GOPATH}/src/github.com/magefile/mage
  - go run bootstrap.go
  - cd ${TRAVIS_BUILD_DIR}
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - mage vendor
  - mage install
  - cd ${TRAVIS_BUILD_DIR}

script:
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    local_dir: public
    skip_cleanup: true
