language: go

go:
  - "1.11"

sudo: false

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="public"
    - BUILD_BRANCH="source"
    - DEPLOY_BRANCH="master"

install:
  - go get -d github.com/gohugoio/hugo
  - cd ${GOPATH:-$HOME/go}/src/github.com/gohugoio/hugo
  - go install
  - cd ${TRAVIS_BUILD_DIR}

script:
  - cd databiosphere
  - hugo

deploy:
  - provider: pages
    edge: true
    github_token: ${GITHUB_TOKEN}
    local_dir: databiosphere/public
    skip_cleanup: true
